using Dominio.Entidades;

namespace Dados.Seed
{
    public static class CargaArquivoFormatoAssinatura
    {
        public static List<object> GerarCarga()
        {
            return new List<object>()
            {
                new ArquivoFormatoAssinatura() { Id = 1, ArquivoFormatoId = 37 },
                new ArquivoFormatoAssinatura() { Id = 2, ArquivoFormatoId = 57 },
                new ArquivoFormatoAssinatura() { Id = 3, ArquivoFormatoId = 57 },
                new ArquivoFormatoAssinatura() { Id = 4, ArquivoFormatoId = 57 },
                new ArquivoFormatoAssinatura() { Id = 5, ArquivoFormatoId = 57 },
                new ArquivoFormatoAssinatura() { Id = 6, ArquivoFormatoId = 57 },
                new ArquivoFormatoAssinatura() { Id = 7, ArquivoFormatoId = 57 },
                new ArquivoFormatoAssinatura() { Id = 8, ArquivoFormatoId = 57 },
                new ArquivoFormatoAssinatura() { Id = 9, ArquivoFormatoId = 57 },
                new ArquivoFormatoAssinatura() { Id = 10, ArquivoFormatoId = 57 },
                new ArquivoFormatoAssinatura() { Id = 11, ArquivoFormatoId = 58 },
                new ArquivoFormatoAssinatura() { Id = 12, ArquivoFormatoId = 58 },
                new ArquivoFormatoAssinatura() { Id = 13, ArquivoFormatoId = 63 },
                new ArquivoFormatoAssinatura() { Id = 14, ArquivoFormatoId = 63 },
                new ArquivoFormatoAssinatura() { Id = 15, ArquivoFormatoId = 12 },
                new ArquivoFormatoAssinatura() { Id = 16, ArquivoFormatoId = 12 },
                new ArquivoFormatoAssinatura() { Id = 17, ArquivoFormatoId = 12 },
                new ArquivoFormatoAssinatura() { Id = 18, ArquivoFormatoId = 12 },
                new ArquivoFormatoAssinatura() { Id = 19, ArquivoFormatoId = 12 },
                new ArquivoFormatoAssinatura() { Id = 20, ArquivoFormatoId = 15 },
                new ArquivoFormatoAssinatura() { Id = 21, ArquivoFormatoId = 18 },
                new ArquivoFormatoAssinatura() { Id = 22, ArquivoFormatoId = 22 },
                new ArquivoFormatoAssinatura() { Id = 23, ArquivoFormatoId = 22 },
                new ArquivoFormatoAssinatura() { Id = 24, ArquivoFormatoId = 22 },
                new ArquivoFormatoAssinatura() { Id = 25, ArquivoFormatoId = 21 },
                new ArquivoFormatoAssinatura() { Id = 26, ArquivoFormatoId = 21 },
                new ArquivoFormatoAssinatura() { Id = 27, ArquivoFormatoId = 21 },
                new ArquivoFormatoAssinatura() { Id = 28, ArquivoFormatoId = 36 },
                new ArquivoFormatoAssinatura() { Id = 29, ArquivoFormatoId = 38 },
                new ArquivoFormatoAssinatura() { Id = 30, ArquivoFormatoId = 38 },
                new ArquivoFormatoAssinatura() { Id = 31, ArquivoFormatoId = 38 },
                new ArquivoFormatoAssinatura() { Id = 32, ArquivoFormatoId = 38 },
                new ArquivoFormatoAssinatura() { Id = 33, ArquivoFormatoId = 38 },
                new ArquivoFormatoAssinatura() { Id = 34, ArquivoFormatoId = 38 },
                new ArquivoFormatoAssinatura() { Id = 35, ArquivoFormatoId = 38 },
                new ArquivoFormatoAssinatura() { Id = 36, ArquivoFormatoId = 40 },
                new ArquivoFormatoAssinatura() { Id = 37, ArquivoFormatoId = 45 },
                new ArquivoFormatoAssinatura() { Id = 38, ArquivoFormatoId = 45 },
                new ArquivoFormatoAssinatura() { Id = 39, ArquivoFormatoId = 45 },
                new ArquivoFormatoAssinatura() { Id = 40, ArquivoFormatoId = 45 },
                new ArquivoFormatoAssinatura() { Id = 41, ArquivoFormatoId = 46 },
                new ArquivoFormatoAssinatura() { Id = 42, ArquivoFormatoId = 46 },
                new ArquivoFormatoAssinatura() { Id = 43, ArquivoFormatoId = 46 },
                new ArquivoFormatoAssinatura() { Id = 44, ArquivoFormatoId = 46 },
                new ArquivoFormatoAssinatura() { Id = 45, ArquivoFormatoId = 59 },
                new ArquivoFormatoAssinatura() { Id = 46, ArquivoFormatoId = 61 },
                new ArquivoFormatoAssinatura() { Id = 47, ArquivoFormatoId = 61 },
                new ArquivoFormatoAssinatura() { Id = 48, ArquivoFormatoId = 61 },
                new ArquivoFormatoAssinatura() { Id = 49, ArquivoFormatoId = 61 },
                new ArquivoFormatoAssinatura() { Id = 50, ArquivoFormatoId = 61 },
                new ArquivoFormatoAssinatura() { Id = 51, ArquivoFormatoId = 61 },
                new ArquivoFormatoAssinatura() { Id = 52, ArquivoFormatoId = 61 },
                new ArquivoFormatoAssinatura() { Id = 53, ArquivoFormatoId = 3 },
                new ArquivoFormatoAssinatura() { Id = 54, ArquivoFormatoId = 3 },
                new ArquivoFormatoAssinatura() { Id = 55, ArquivoFormatoId = 3 },
                new ArquivoFormatoAssinatura() { Id = 56, ArquivoFormatoId = 3 },
                new ArquivoFormatoAssinatura() { Id = 57, ArquivoFormatoId = 3 },
                new ArquivoFormatoAssinatura() { Id = 58, ArquivoFormatoId = 3 },
                new ArquivoFormatoAssinatura() { Id = 59, ArquivoFormatoId = 4 },
                new ArquivoFormatoAssinatura() { Id = 60, ArquivoFormatoId = 6 },
                new ArquivoFormatoAssinatura() { Id = 61, ArquivoFormatoId = 8 },
                new ArquivoFormatoAssinatura() { Id = 62, ArquivoFormatoId = 9 },
                new ArquivoFormatoAssinatura() { Id = 63, ArquivoFormatoId = 20 },
                new ArquivoFormatoAssinatura() { Id = 64, ArquivoFormatoId = 20 },
                new ArquivoFormatoAssinatura() { Id = 65, ArquivoFormatoId = 20 },
                new ArquivoFormatoAssinatura() { Id = 66, ArquivoFormatoId = 20 },
                new ArquivoFormatoAssinatura() { Id = 67, ArquivoFormatoId = 21 },
                new ArquivoFormatoAssinatura() { Id = 68, ArquivoFormatoId = 22 },
                new ArquivoFormatoAssinatura() { Id = 69, ArquivoFormatoId = 29 },
                new ArquivoFormatoAssinatura() { Id = 70, ArquivoFormatoId = 31 },
                new ArquivoFormatoAssinatura() { Id = 71, ArquivoFormatoId = 32 },
                new ArquivoFormatoAssinatura() { Id = 72, ArquivoFormatoId = 33 },
                new ArquivoFormatoAssinatura() { Id = 73, ArquivoFormatoId = 34 },
                new ArquivoFormatoAssinatura() { Id = 74, ArquivoFormatoId = 39 },
                new ArquivoFormatoAssinatura() { Id = 75, ArquivoFormatoId = 43 },
                new ArquivoFormatoAssinatura() { Id = 76, ArquivoFormatoId = 43 },
                new ArquivoFormatoAssinatura() { Id = 77, ArquivoFormatoId = 44 },
                new ArquivoFormatoAssinatura() { Id = 78, ArquivoFormatoId = 49 },
                new ArquivoFormatoAssinatura() { Id = 79, ArquivoFormatoId = 50 }
            };
        }
    }
}
