//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multilingua.Campos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Campos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Campos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multilingua.Campos.Campos", typeof(Campos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto Valor.
        /// </summary>
        public static string AltoValor {
            get {
                return ResourceManager.GetString("AltoValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado Por.
        /// </summary>
        public static string AprovadoPor {
            get {
                return ResourceManager.GetString("AprovadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixo Valor.
        /// </summary>
        public static string BaixoValor {
            get {
                return ResourceManager.GetString("BaixoValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string Bloqueado {
            get {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado.
        /// </summary>
        public static string Cancelado {
            get {
                return ResourceManager.GetString("Cancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro Custo Descrição.
        /// </summary>
        public static string CentroCustoDescricao {
            get {
                return ResourceManager.GetString("CentroCustoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro Custo Nome.
        /// </summary>
        public static string CentroCustoNome {
            get {
                return ResourceManager.GetString("CentroCustoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string Classificacao {
            get {
                return ResourceManager.GetString("Classificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Ativo.
        /// </summary>
        public static string CodigoAtivo {
            get {
                return ResourceManager.GetString("CodigoAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Cliente.
        /// </summary>
        public static string CodigoCliente {
            get {
                return ResourceManager.GetString("CodigoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Conta.
        /// </summary>
        public static string CodigoConta {
            get {
                return ResourceManager.GetString("CodigoConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Empresa.
        /// </summary>
        public static string CodigoEmpresa {
            get {
                return ResourceManager.GetString("CodigoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Evento.
        /// </summary>
        public static string CodigoEvento {
            get {
                return ResourceManager.GetString("CodigoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Material.
        /// </summary>
        public static string CodigoMaterial {
            get {
                return ResourceManager.GetString("CodigoMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        public static string Conta {
            get {
                return ResourceManager.GetString("Conta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Contábil.
        /// </summary>
        public static string ContaContabil {
            get {
                return ResourceManager.GetString("ContaContabil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        public static string Contato {
            get {
                return ResourceManager.GetString("Contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato Código.
        /// </summary>
        public static string ContratoCodigo {
            get {
                return ResourceManager.GetString("ContratoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado Por.
        /// </summary>
        public static string CriadoPor {
            get {
                return ResourceManager.GetString("CriadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Admissão.
        /// </summary>
        public static string DataAdmissao {
            get {
                return ResourceManager.GetString("DataAdmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Afastamento.
        /// </summary>
        public static string DataAfastamento {
            get {
                return ResourceManager.GetString("DataAfastamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Afastamento Retorno.
        /// </summary>
        public static string DataAfastamentoRetorno {
            get {
                return ResourceManager.GetString("DataAfastamentoRetorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Alteração.
        /// </summary>
        public static string DataAlteracao {
            get {
                return ResourceManager.GetString("DataAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Aquisição.
        /// </summary>
        public static string DataAquisicao {
            get {
                return ResourceManager.GetString("DataAquisicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Cadastro.
        /// </summary>
        public static string DataCadastro {
            get {
                return ResourceManager.GetString("DataCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Cancelamento.
        /// </summary>
        public static string DataCancelamento {
            get {
                return ResourceManager.GetString("DataCancelamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Criação.
        /// </summary>
        public static string DataCriacao {
            get {
                return ResourceManager.GetString("DataCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Desligamento.
        /// </summary>
        public static string DataDesligamento {
            get {
                return ResourceManager.GetString("DataDesligamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Documento.
        /// </summary>
        public static string DataDocumento {
            get {
                return ResourceManager.GetString("DataDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Emissão.
        /// </summary>
        public static string DataEmissao {
            get {
                return ResourceManager.GetString("DataEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Emissão Nota Fiscal.
        /// </summary>
        public static string DataEmissaoNotaFiscal {
            get {
                return ResourceManager.GetString("DataEmissaoNotaFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Emissão Nota Fiscal Saída.
        /// </summary>
        public static string DataEmissaoNotaFiscalSaida {
            get {
                return ResourceManager.GetString("DataEmissaoNotaFiscalSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entrada.
        /// </summary>
        public static string DataEntrada {
            get {
                return ResourceManager.GetString("DataEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final Últimas Férias.
        /// </summary>
        public static string DataFinalUltimasFerias {
            get {
                return ResourceManager.GetString("DataFinalUltimasFerias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Lançamento.
        /// </summary>
        public static string DataLancamento {
            get {
                return ResourceManager.GetString("DataLancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Liberação.
        /// </summary>
        public static string DataLiberacao {
            get {
                return ResourceManager.GetString("DataLiberacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Pagamento.
        /// </summary>
        public static string DataPagamento {
            get {
                return ResourceManager.GetString("DataPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Recebimento.
        /// </summary>
        public static string DataRecebimento {
            get {
                return ResourceManager.GetString("DataRecebimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Requisição.
        /// </summary>
        public static string DataRequisicao {
            get {
                return ResourceManager.GetString("DataRequisicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Última Alteração.
        /// </summary>
        public static string DataUltimaAlteracao {
            get {
                return ResourceManager.GetString("DataUltimaAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Último Exame Periódico.
        /// </summary>
        public static string DataUltimoExamePeriodico {
            get {
                return ResourceManager.GetString("DataUltimoExamePeriodico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Vencimento.
        /// </summary>
        public static string DataVencimento {
            get {
                return ResourceManager.GetString("DataVencimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconto.
        /// </summary>
        public static string Desconto {
            get {
                return ResourceManager.GetString("Desconto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Conta.
        /// </summary>
        public static string DescricaoConta {
            get {
                return ResourceManager.GetString("DescricaoConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Cliente.
        /// </summary>
        public static string DocumentoCliente {
            get {
                return ResourceManager.GetString("DocumentoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Compensação.
        /// </summary>
        public static string DocumentoCompensacao {
            get {
                return ResourceManager.GetString("DocumentoCompensacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Credor.
        /// </summary>
        public static string DocumentoCredor {
            get {
                return ResourceManager.GetString("DocumentoCredor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Fornecedor.
        /// </summary>
        public static string DocumentoFornecedor {
            get {
                return ResourceManager.GetString("DocumentoFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Inventário.
        /// </summary>
        public static string EmInventario {
            get {
                return ResourceManager.GetString("EmInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Código.
        /// </summary>
        public static string EmpresaCodigo {
            get {
                return ResourceManager.GetString("EmpresaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento.
        /// </summary>
        public static string Evento {
            get {
                return ResourceManager.GetString("Evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasia.
        /// </summary>
        public static string Fantasia {
            get {
                return ResourceManager.GetString("Fantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor Código.
        /// </summary>
        public static string FornecedorCodigo {
            get {
                return ResourceManager.GetString("FornecedorCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor Documento.
        /// </summary>
        public static string FornecedorDocumento {
            get {
                return ResourceManager.GetString("FornecedorDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor Internacional.
        /// </summary>
        public static string FornecedorInternacional {
            get {
                return ResourceManager.GetString("FornecedorInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor Nome.
        /// </summary>
        public static string FornecedorNome {
            get {
                return ResourceManager.GetString("FornecedorNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string Hora {
            get {
                return ResourceManager.GetString("Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição Estadual.
        /// </summary>
        public static string InscricaoEstadual {
            get {
                return ResourceManager.GetString("InscricaoEstadual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição Municipal.
        /// </summary>
        public static string InscricaoMunicipal {
            get {
                return ResourceManager.GetString("InscricaoMunicipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Código.
        /// </summary>
        public static string ItemCodigo {
            get {
                return ResourceManager.GetString("ItemCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Descrição.
        /// </summary>
        public static string ItemDescricao {
            get {
                return ResourceManager.GetString("ItemDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juros.
        /// </summary>
        public static string Juros {
            get {
                return ResourceManager.GetString("Juros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        public static string Logradouro {
            get {
                return ResourceManager.GetString("Logradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Código.
        /// </summary>
        public static string MaterialCodigo {
            get {
                return ResourceManager.GetString("MaterialCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        public static string Matricula {
            get {
                return ResourceManager.GetString("Matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês.
        /// </summary>
        public static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês Ano Referência.
        /// </summary>
        public static string MesAnoReferencia {
            get {
                return ResourceManager.GetString("MesAnoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês Referência.
        /// </summary>
        public static string MesReferencia {
            get {
                return ResourceManager.GetString("MesReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multa.
        /// </summary>
        public static string Multa {
            get {
                return ResourceManager.GetString("Multa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Município.
        /// </summary>
        public static string Municipio {
            get {
                return ResourceManager.GetString("Municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Cliente.
        /// </summary>
        public static string NomeCliente {
            get {
                return ResourceManager.GetString("NomeCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Credor.
        /// </summary>
        public static string NomeCredor {
            get {
                return ResourceManager.GetString("NomeCredor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Fornecedor.
        /// </summary>
        public static string NomeFornecedor {
            get {
                return ResourceManager.GetString("NomeFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Nota Fiscal.
        /// </summary>
        public static string NumeroNotaFiscal {
            get {
                return ResourceManager.GetString("NumeroNotaFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Nota Fiscal Saída.
        /// </summary>
        public static string NumeroNotaFiscalSaida {
            get {
                return ResourceManager.GetString("NumeroNotaFiscalSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Parcela.
        /// </summary>
        public static string NumeroParcela {
            get {
                return ResourceManager.GetString("NumeroParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem Compra Código.
        /// </summary>
        public static string OrdemCompraCodigo {
            get {
                return ResourceManager.GetString("OrdemCompraCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCD.
        /// </summary>
        public static string PCD {
            get {
                return ResourceManager.GetString("PCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido Código.
        /// </summary>
        public static string PedidoCodigo {
            get {
                return ResourceManager.GetString("PedidoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido Compra Tipo Descrição.
        /// </summary>
        public static string PedidoCompraTipoDescricao {
            get {
                return ResourceManager.GetString("PedidoCompraTipoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão Lançamento Contábil Manual.
        /// </summary>
        public static string PermissaoLancamentoContabilManual {
            get {
                return ResourceManager.GetString("PermissaoLancamentoContabilManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto Descrição.
        /// </summary>
        public static string ProdutoDescricao {
            get {
                return ResourceManager.GetString("ProdutoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string Quantidade {
            get {
                return ResourceManager.GetString("Quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário.
        /// </summary>
        public static string Salario {
            get {
                return ResourceManager.GetString("Salario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Série.
        /// </summary>
        public static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Baixa.
        /// </summary>
        public static string TipoBaixa {
            get {
                return ResourceManager.GetString("TipoBaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Condição Pagamento.
        /// </summary>
        public static string TipoCondicaoPagamento {
            get {
                return ResourceManager.GetString("TipoCondicaoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Evento.
        /// </summary>
        public static string TipoEvento {
            get {
                return ResourceManager.GetString("TipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Lançamento.
        /// </summary>
        public static string TipoLancamento {
            get {
                return ResourceManager.GetString("TipoLancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Lançamento Contábil.
        /// </summary>
        public static string TipoLancamentoContabil {
            get {
                return ResourceManager.GetString("TipoLancamentoContabil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Natureza.
        /// </summary>
        public static string TipoNatureza {
            get {
                return ResourceManager.GetString("TipoNatureza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Parcelas.
        /// </summary>
        public static string TotalParcelas {
            get {
                return ResourceManager.GetString("TotalParcelas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string UF {
            get {
                return ResourceManager.GetString("UF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário Email.
        /// </summary>
        public static string UsuarioEmail {
            get {
                return ResourceManager.GetString("UsuarioEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Aquisição.
        /// </summary>
        public static string ValorAquisicao {
            get {
                return ResourceManager.GetString("ValorAquisicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Depreciação Acumulada.
        /// </summary>
        public static string ValorDepreciacaoAcumulada {
            get {
                return ResourceManager.GetString("ValorDepreciacaoAcumulada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Depreciação Mensal.
        /// </summary>
        public static string ValorDepreciacaoMensal {
            get {
                return ResourceManager.GetString("ValorDepreciacaoMensal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Desconto.
        /// </summary>
        public static string ValorDesconto {
            get {
                return ResourceManager.GetString("ValorDesconto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Faturado.
        /// </summary>
        public static string ValorFaturado {
            get {
                return ResourceManager.GetString("ValorFaturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Nota Fiscal Saída.
        /// </summary>
        public static string ValorNotaFiscalSaida {
            get {
                return ResourceManager.GetString("ValorNotaFiscalSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Padrão.
        /// </summary>
        public static string ValorPadrao {
            get {
                return ResourceManager.GetString("ValorPadrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Parcela.
        /// </summary>
        public static string ValorParcela {
            get {
                return ResourceManager.GetString("ValorParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Recebido.
        /// </summary>
        public static string ValorRecebido {
            get {
                return ResourceManager.GetString("ValorRecebido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total.
        /// </summary>
        public static string ValorTotal {
            get {
                return ResourceManager.GetString("ValorTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Unitário.
        /// </summary>
        public static string ValorUnitario {
            get {
                return ResourceManager.GetString("ValorUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vida Útil Meses.
        /// </summary>
        public static string VidaUtilMeses {
            get {
                return ResourceManager.GetString("VidaUtilMeses", resourceCulture);
            }
        }
    }
}
