//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multilingua.AlertasNotificacoes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlertasNotificacoes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlertasNotificacoes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multilingua.AlertasNotificacoes.AlertasNotificacoes", typeof(AlertasNotificacoes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso negado.
        /// </summary>
        public static string AcessoNegado {
            get {
                return ResourceManager.GetString("AcessoNegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo não encontrado.
        /// </summary>
        public static string ArquivoNaoEncontrado {
            get {
                return ResourceManager.GetString("ArquivoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sheet informada não existe.
        /// </summary>
        public static string ASheetInformadaNaoExiste {
            get {
                return ResourceManager.GetString("ASheetInformadaNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpo não pode ser vazio.
        /// </summary>
        public static string CorpoNaoPodeSerVazio {
            get {
                return ResourceManager.GetString("CorpoNaoPodeSerVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados inválidos.
        /// </summary>
        public static string DadosInvalidos {
            get {
                return ResourceManager.GetString("DadosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatário ou remetente não encontrados.
        /// </summary>
        public static string DestinatarioOuRemetenteNaoEncontrados {
            get {
                return ResourceManager.GetString("DestinatarioOuRemetenteNaoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro..
        /// </summary>
        public static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato não suportado.
        /// </summary>
        public static string FormatoNaoSuportado {
            get {
                return ResourceManager.GetString("FormatoNaoSuportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função indisponível no momento.
        /// </summary>
        public static string FuncaoIndisponivelNoMomento {
            get {
                return ResourceManager.GetString("FuncaoIndisponivelNoMomento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout inválido - posição inválida.
        /// </summary>
        public static string LayoutInvalidoPosicaoInvalida {
            get {
                return ResourceManager.GetString("LayoutInvalidoPosicaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout inválido - quantidade de colunas.
        /// </summary>
        public static string LayoutInvalidoQuantidadeColunas {
            get {
                return ResourceManager.GetString("LayoutInvalidoQuantidadeColunas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout não definido.
        /// </summary>
        public static string LayoutNaoDefinido {
            get {
                return ResourceManager.GetString("LayoutNaoDefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método não reconhecido para o tipo.
        /// </summary>
        public static string MetodoNaoReconhecidoParaOTipo {
            get {
                return ResourceManager.GetString("MetodoNaoReconhecidoParaOTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível conectar ao servidor.
        /// </summary>
        public static string NaoFoiPossivelConectarAoServidor {
            get {
                return ResourceManager.GetString("NaoFoiPossivelConectarAoServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível ler o arquivo.
        /// </summary>
        public static string NaoFoiPossivelLerOArquivo {
            get {
                return ResourceManager.GetString("NaoFoiPossivelLerOArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha na solicitação.
        /// </summary>
        public static string OcorreuUmaFalhaNaSolicitacao {
            get {
                return ResourceManager.GetString("OcorreuUmaFalhaNaSolicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha os dados corretamente.
        /// </summary>
        public static string PreenchaOsDadosCorretamente {
            get {
                return ResourceManager.GetString("PreenchaOsDadosCorretamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema indisponível no momento.
        /// </summary>
        public static string SistemaIndisponivelNoMomento {
            get {
                return ResourceManager.GetString("SistemaIndisponivelNoMomento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        public static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário bloqueado por multiplas tentativas de login..
        /// </summary>
        public static string UsuarioBloqueadoPorMultiplasTentativas {
            get {
                return ResourceManager.GetString("UsuarioBloqueadoPorMultiplasTentativas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha incorreto.
        /// </summary>
        public static string UsuarioOuSenhaIncorreto {
            get {
                return ResourceManager.GetString("UsuarioOuSenhaIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos.
        /// </summary>
        public static string UsuarioOuSenhaInvalidos {
            get {
                return ResourceManager.GetString("UsuarioOuSenhaInvalidos", resourceCulture);
            }
        }
    }
}
